#!/usr/bin/env python

import subprocess
import sys

PRIMARY = [str(i) for i in range(1, 13)]
SECONDARY = [str(i) for i in range(13, 25)]

TO_PRIMARY = {i: j for i, j in zip(PRIMARY, SECONDARY)}
TO_SECONDARY = {i: j for i, j in zip(SECONDARY, PRIMARY)}

mapping = TO_PRIMARY

if len(sys.argv) > 1 and sys.argv[1] == "2":
    mapping = TO_SECONDARY

for source_workspace, target_workspace in mapping.items():
    list_output = subprocess.run(
        ["aerospace", "list-windows", "--workspace", source_workspace],
        capture_output=True,
        encoding="utf-8",
    ).stdout
    windows = [item.split("|")[0].strip() for item in list_output.splitlines()]
    for window_id in windows:
        subprocess.run(
            [
                "aerospace",
                "move-node-to-workspace",
                "--window-id",
                window_id,
                target_workspace,
            ]
        )
