#!/usr/bin/env -S uv run --script

# /// script
# requires-python = ">=3.11"
# dependencies = ["plumbum"]
# ///

import argparse
from pathlib import Path

from plumbum.cmd import uv


def main():
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("script", type=Path)
    python_executable = Path(
        uv[
            "python",
            "find",
            "--script",
            parser.parse_args().script,
        ]()
    )
    activate_script = python_executable.parent / "activate"
    assert activate_script.exists(), f"Activate script not found: {activate_script}"
    print(f"{activate_script}")


if __name__ == "__main__":
    main()
